"""tenant api_key_hash

Revision ID: 74a0401b2048
Revises: a2ae57f9421a
Create Date: 2026-09-04 22:03:43.357755

"""

from collections.abc import Sequence

import pgvector.sqlalchemy  # noqa: F401
import sqlalchemy as sa
from alembic import op

revision: str = "74a0401b2048"
down_revision: str | None = "a2ae57f9421a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tenant", sa.Column("api_key_hash", sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, "tenant", ["api_key_hash"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tenant", type_="unique")
    op.drop_column("tenant", "api_key_hash")
    # ### end Alembic commands ###
