"""knowledge_item_chunk

Revision ID: 903610e1e97f
Revises: 74a0401b2048
Create Date: 2026-09-04 23:40:50.006211

"""

from collections.abc import Sequence

import pgvector.sqlalchemy  # noqa: F401
import sqlalchemy as sa
from alembic import op

revision: str = "903610e1e97f"
down_revision: str | None = "74a0401b2048"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "knowledge_item_chunk",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("knowledge_item_id", sa.UUID(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["knowledge_item_id"], ["knowledge_item.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("knowledge_item_id", "chunk_index"),
    )
    op.create_index(
        op.f("ix_knowledge_item_chunk_content_hash"),
        "knowledge_item_chunk",
        ["content_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_knowledge_item_chunk_tenant_id"),
        "knowledge_item_chunk",
        ["tenant_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_knowledge_item_chunk_tenant_id"), table_name="knowledge_item_chunk")
    op.drop_index(op.f("ix_knowledge_item_chunk_content_hash"), table_name="knowledge_item_chunk")
    op.drop_table("knowledge_item_chunk")
    # ### end Alembic commands ###
