"""team_member tenant_id

Revision ID: a2ae57f9421a
Revises: f82a30c9357c
Create Date: 2026-09-04 20:12:59.936891

"""

from collections.abc import Sequence

import pgvector.sqlalchemy  # noqa: F401
import sqlalchemy as sa
from alembic import op

revision: str = "a2ae57f9421a"
down_revision: str | None = "f82a30c9357c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("team_member", sa.Column("tenant_id", sa.UUID(), nullable=False))
    op.create_index(op.f("ix_team_member_tenant_id"), "team_member", ["tenant_id"], unique=False)
    op.create_foreign_key(None, "team_member", "tenant", ["tenant_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "team_member", type_="foreignkey")
    op.drop_index(op.f("ix_team_member_tenant_id"), table_name="team_member")
    op.drop_column("team_member", "tenant_id")
    # ### end Alembic commands ###
