"""scan_finding tenant_id

Revision ID: f82a30c9357c
Revises: a946b2a30709
Create Date: 2026-09-04 20:12:26.063641

"""

from collections.abc import Sequence

import pgvector.sqlalchemy  # noqa: F401
import sqlalchemy as sa
from alembic import op

revision: str = "f82a30c9357c"
down_revision: str | None = "a946b2a30709"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("scan_finding", sa.Column("tenant_id", sa.UUID(), nullable=False))
    op.create_index(op.f("ix_scan_finding_tenant_id"), "scan_finding", ["tenant_id"], unique=False)
    op.create_foreign_key(None, "scan_finding", "tenant", ["tenant_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "scan_finding", type_="foreignkey")
    op.drop_index(op.f("ix_scan_finding_tenant_id"), table_name="scan_finding")
    op.drop_column("scan_finding", "tenant_id")
    # ### end Alembic commands ###
